# Site location
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcuscraske.com" # the base hostname & protocol for your site, e.g. http://example.com
destination: docs/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - yui-compressor
  - jekyll-sitemap
  - jekyll-webp

exclude:
  - Gemfile
  - Gemfile.lock
  - run.sh
  - README.md
  - package.json
  - package-lock.json
  - deployment
  - node_modules
  - asset-sources
  - limpygnome-dot-com.iml
  - marcuscraske-dot-com.iml

# Assets
assets:
  compression: true
  gzip: true
  compress:
    css: true
  autowrite: true
  prefix: "/assets"
  sources:
    - assets

# Posts
permalink: pretty
paginate: 5
paginate_path: "page:num"
excerpt_separator: "#"

# Collections
collections:
  projects:
    output: true

highlighter: rouge

# Compress images to webp
webp:
  enabled: true
  quality: 100
  img_dir: ["/assets/", "/_assets/"]
  nested: true
  formats: [".jpeg", ".jpg", ".png"]
  gifs: [".gifs"]
  regenerate: false
  webp_path: nil
  exclude: []
  append_ext: false
