# Site location
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcuscraske.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - run.sh
  - README.md

# Assets
assets:
  compress:
    css: true
  autowrite: true
  prefix: "/assets"
  sources:
    - assets

# Posts
permalink: pretty
paginate: 5
paginate_path: "page:num"
excerpt_separator: "#"

# Collections
collections:
  projects:
    output: true

highlighter: rouge
